blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.gg/DtuKCEkXzY
    about: For quick support or questions, join our Discord server.
  - name: Bot Website
    url: https://hoyo-code.chiraitori.me
    about: Visit our website for documentation and updates.
